import React, { useState, useRef } from 'react';
import {Button, Grid, Header} from 'semantic-ui-react'
import {useDispatch, useSelector} from "react-redux";
import {useTranslation} from "react-i18next";
import {setComponent} from "../actions/component";
import MainMenu from "./MainMenu";
import {getRandomElementFromArray, getRandomInt} from "../util/util";
import {chordDefinitions} from "../util/intervals";
import MIDISounds from 'midi-sounds-react';
import {setNegativeMessage, setPositiveMessage} from "../actions/headerMessage";


// antakse ette
// lihtsaim variant: mängib akordi, vasta, kas maz või min
// meloodilist mitte
const AskChord = () => {
    const { t, i18n } = useTranslation();
    const dispatch = useDispatch();

    //const type = Mm
    // 1 - mažoor ja minoor
    // vaja -  lubatud akordid
    //const isHarmonic = useSelector(state => state.exerciseReducer.isHarmonic);
    //const isTonic = useSelector(state => state.exerciseReducer.isTonic);
    const name = useSelector(state => state.exerciseReducer.name);
    const type = useSelector(state => state.exerciseReducer.type);
    const midiSounds = useRef(null);

    const [interval, setInterval] = useState({});
    const [exerciseHasBegun, setExerciseHasBegun] = useState(false);
    const [possibleChords, setPossibleChords] = useState([]);
    const [selectedChord, setSelectedChord] = useState([]);
    const [answer, setAnswer] = useState(null);
    //const [isMajor, setIsMajor] = useState(true);
    //const [selectedTonicNote, setSelectedTonicNote] = useState(null);
    // let answer = null; // answer -  generated by exercise, correct
    // response - users input, can be wright or wrong
    // let selectedChord = null;
    // let possibleChords = [];
    let baseMidiNote = 60;

    // EXERCISE LOGIC ======================================

    const startExercise = () => {
        setExerciseHasBegun(true);
        // what is right place for setting the volume?
        midiSounds.current.setMasterVolume(0.3); // not too loud TODO: add control slider
        //console.log("Chords name:", name);

        //askChord1(); // check for type...

        let possibleChords = [];

        switch(name) {
            case "MmTriad":
                possibleChords.push(
                    chordDefinitions.find( chord => chord.shortName === "M" ),
                    chordDefinitions.find( chord => chord.shortName === "m" )
                );
                break;
            case "MmdaTriad":
                possibleChords.push(
                    chordDefinitions.find( chord => chord.shortName === "M" ),
                    chordDefinitions.find( chord => chord.shortName === "m" ),
                    chordDefinitions.find( chord => chord.shortName === "<kk" ),
                    chordDefinitions.find( chord => chord.shortName === ">kk" ),
                );
                break;
            default:
                console.log("no exercise found");
                return;
        }

        setPossibleChords(possibleChords);

        renew(possibleChords);

        // test:
        //createResponseButtons();
    };


    // renew generates answer and performs play/show
    const renew = (possibleChords) =>  {
        baseMidiNote = getRandomInt(53, 72); // TODO: make the range configurable
        const selectedChord = getRandomElementFromArray(possibleChords);
        setSelectedChord(selectedChord);
        console.log("Selected chord: ", selectedChord.longName)
        const answer = {shortName: selectedChord.shortName}; // may be different in different exercised, might need switch/case
        setAnswer(answer);
        play(selectedChord);
    };

    // what is more generic name -  perform? execute? present?
    const play = (selectedChord) => {
        const duration = 4; // TODO: make configurable
        const midiNotes = [];
        for (let midiInterval of selectedChord.midiIntervals) { // nootide kaupa basenote + interval
            midiNotes.push(baseMidiNote + midiInterval);
        }
        console.log("Midinotes played: ", midiNotes);
        midiSounds.current.playChordNow(3, midiNotes, duration);

    };

    const checkResponse = (response) => { // response is an object {key: value [, key2: value, ...]}
        //console.log(response);
        const correctChord = selectedChord.longName; // TODO: translation

        if ( JSON.stringify(response) === JSON.stringify(answer)) {
            dispatch(setPositiveMessage(`${t("correctAnswerIs")} ${correctChord}`, 5000));
        } else {
            dispatch(setNegativeMessage(`${t("correctAnswerIs")} ${correctChord}`, 5000));
        }
    };

    // UI ======================================================

    const goBack = () => {
        dispatch(setComponent("MainMenu"));
    };

    const createPlaySoundButton = () => {
        console.log("Begun: ", exerciseHasBegun);
        // console.log("Begun: ", exerciseHasBegun());
        // if (exerciseHasBegun()) {
        if (exerciseHasBegun) {
            return <Button color={"green"} onClick={() => renew(possibleChords)}  className={"fullWidth marginTopSmall"}>{t("playNext")}</Button>
        } else {
            return <Button color={"green"} onClick={startExercise} className={"fullWidth marginTopSmall"}>{t("startExercise")}</Button>
        }
    };

    const createResponseButtons = () => {
        let rows = [];

        for (let i = 0, n = possibleChords.length; i < n; i += 2) {
            const row = createResponseButtonRow(possibleChords[i], possibleChords[i + 1]);
            rows.push(row);
        }

        return rows;
    };

    const createResponseButtonRow = (chord1, chord2) => {
        return (
            <Grid.Row columns={2}>
                {createResponseButtonColumn(chord1)}
                {createResponseButtonColumn(chord2)}
            </Grid.Row>
        )
    };

    const createResponseButtonColumn = (chord) => {
        return (
            <Grid.Column>
                <Button className={"exerciseBtn"}
                        onClick={() => checkResponse({shortName: chord.shortName})}>{chord.longName}</Button>
            </Grid.Column>
        )
    };


    // TODO: generate answer buttons according to possibleChords list
    // proovisin createResponseButtons, aga ei töötanud
    return (
        <div>
            <Header size='large'>{`${t(name)} }`}</Header>
            <Grid>
                {createResponseButtons()}
            {/*    <Grid.Row columns={2}>*/}
                {/*    <Grid.Column>*/}
                {/*        <Button onClick={() => checkResponse({shortName: "M"})} className={"exerciseBtn"}>{t("majorTriad")}</Button>*/}
                {/*    </Grid.Column>*/}
                {/*    <Grid.Column>*/}
                {/*        <Button onClick={() => checkResponse({shortName: "m"})} className={"exerciseBtn"}>{t("minorTriad")}</Button>*/}
                {/*    </Grid.Column>*/}
                {/*</Grid.Row>*/}

                {/*<Grid.Row columns={2}>*/}
                {/*    <Grid.Column>*/}
                {/*        <Button onClick={() => checkResponse({shortName: "<kk"})} className={"exerciseBtn"}>{t("diminishedTriad")}</Button>*/}
                {/*    </Grid.Column>*/}
                {/*    <Grid.Column>*/}
                {/*        <Button onClick={() => checkResponse({shortName: ">kk"})} className={"exerciseBtn"}>{t("augmentedTriad")}</Button>*/}
                {/*    </Grid.Column>*/}
                {/*</Grid.Row>*/}

                <Grid.Row>
                    <Grid.Column>
                        {createPlaySoundButton()}
                        <Button onClick={goBack} className={"fullWidth marginTopSmall"}>{t("goBack")}</Button>
                    </Grid.Column>
                </Grid.Row>
            </Grid>
            <MIDISounds ref={midiSounds} appElementName="root" instruments={[3]} />
        </div>
    );
};

export default AskChord;