import React, { useState, useRef } from 'react';
import {Button, Grid, Header} from 'semantic-ui-react'
import {useDispatch, useSelector} from "react-redux";
import {useTranslation} from "react-i18next";
import {setComponent} from "../actions/component";
import MainMenu from "./MainMenu";
import {getRandomElementFromArray, getRandomInt} from "../util/util";
import {chordDefinitions} from "../util/intervals";
import MIDISounds from 'midi-sounds-react';
import {setNegativeMessage, setPositiveMessage} from "../actions/headerMessage";


// antakse ette
// lihtsaim variant: mängib akordi, vasta, kas maz või min
// meloodilist mitte
const AskChord = () => {
    const { t, i18n } = useTranslation();
    const dispatch = useDispatch();

    //const type = Mm
    // 1 - mažoor ja minoor
    // vaja -  lubatud akordid
    //const isHarmonic = useSelector(state => state.exerciseReducer.isHarmonic);
    //const isTonic = useSelector(state => state.exerciseReducer.isTonic);
    const name = useSelector(state => state.exerciseReducer.name);
    const type = useSelector(state => state.exerciseReducer.type);
    const midiSounds = useRef(null);

    const [interval, setInterval] = useState({});
    //const [isMajor, setIsMajor] = useState(true);
    //const [selectedTonicNote, setSelectedTonicNote] = useState(null);
    let answer = null; // answer -  generated by exercise, correct
    // response - users input, can be wright or wrong
    let selectedChord = null;
    let possibleChords = [];
    let baseMidiNote = 60;

    // EXERCISE LOGIC ======================================

    const startExercise = () => {
        // what is right place for setting the volume?
        midiSounds.current.setMasterVolume(0.3); // not too loud TODO: add control slider
        //console.log("Chords name:", name);

        //askChord1(); // check for type...
        switch(name) {
            case "MmTriad":
                possibleChords = [
                    chordDefinitions.find( chord => chord.shortName === "M" ),
                    chordDefinitions.find( chord => chord.shortName === "m" )
                ];
                break;
            case "MmdaTriad":
                possibleChords = [
                    chordDefinitions.find( chord => chord.shortName === "M" ),
                    chordDefinitions.find( chord => chord.shortName === "m" ),
                    chordDefinitions.find( chord => chord.shortName === "<kk" ),
                    chordDefinitions.find( chord => chord.shortName === ">kk" ),
                ];
                break;
            default:
                console.log("no exercise found");
                return;
        }
        renew();

        // test:
        //createResponseButtons();
    };


    // renew generates answer and performs play/show
    const renew = () =>  {
        baseMidiNote = getRandomInt(53, 72); // TODO: make the range configurable
        selectedChord = getRandomElementFromArray(possibleChords);
        console.log("Selected chord: ", selectedChord.longName)
        answer = {shortName: selectedChord.shortName}; // may be different in different exercised, might need switch/case
        play();
    };

    // what is more generic name -  perform? execute? present?
    const play = () => {
        const duration = 4; // TODO: make configurable
        const midiNotes = [];
        for (let midiInterval of selectedChord.midiIntervals) { // nootide kaupa basenote + interval
            midiNotes.push(baseMidiNote + midiInterval);
        }
        console.log("Midinotes played: ", midiNotes);
        midiSounds.current.playChordNow(3, midiNotes, duration);

    };

    const checkResponse = (response) => { // response is an object {key: value [, key2: value, ...]}
        //console.log(response);
        const correctChord = selectedChord.longName; // TODO: translation

        if ( JSON.stringify(response) === JSON.stringify(answer)) {
            dispatch(setPositiveMessage(`${t("correctAnswerIs")} ${correctChord}`, 5000));
        } else {
            dispatch(setNegativeMessage(`${t("correctAnswerIs")} ${correctChord}`, 5000));
        }
    };

    const exerciseHasBegun = () => {
        return selectedChord !== null;
    };

    // UI ======================================================

    const goBack = () => {
        dispatch(setComponent("MainMenu"));
    };

    const createPlaySoundButton = () => {
        console.log("Begun: ", exerciseHasBegun());
        if (exerciseHasBegun()) {
            return <Button color={"green"} onClick={renew}  className={"fullWidth marginTopSmall"}>{t("playNext")}</Button>
        } else {
            return <Button color={"green"} onClick={startExercise} className={"fullWidth marginTopSmall"}>{t("startExercise")}</Button>
        }
    };


    const createResponseButtons = () => {
        let component = "";
        let counter = 0;
        const columns = 2;
        for (let chord of possibleChords) {
            // if ( counter%columns === 0) {
            //     component += //new row
            // }
            component += "<Grid.Column>\n";
            component +=  '<Button onClick={() => checkResponse({shortName: "' + chord.shortName +
            '"})} className={"exerciseBtn"}>' + chord.longName +  '</Button>\n'; // TODO: translation!
            component += "</Grid.Column>\n";
        }
        console.log(component);
        return component;
    };


    // TODO: generate answer buttons according to possibleChords list
    // proovisin createResponseButtons, aga ei töötanud
    return (
        <div>
            <Header size='large'>{`${t(name)} }`}</Header>
            <Grid>
                <Grid.Row columns={2}>
                    <Grid.Column>
                        <Button onClick={() => checkResponse({shortName: "M"})} className={"exerciseBtn"}>{t("majorTriad")}</Button>
                    </Grid.Column>
                    <Grid.Column>
                        <Button onClick={() => checkResponse({shortName: "m"})} className={"exerciseBtn"}>{t("minorTriad")}</Button>
                    </Grid.Column>
                </Grid.Row>

                <Grid.Row columns={2}>
                    <Grid.Column>
                        <Button onClick={() => checkResponse({shortName: "<kk"})} className={"exerciseBtn"}>{t("diminishedTriad")}</Button>
                    </Grid.Column>
                    <Grid.Column>
                        <Button onClick={() => checkResponse({shortName: ">kk"})} className={"exerciseBtn"}>{t("augmentedTriad")}</Button>
                    </Grid.Column>
                </Grid.Row>

                <Grid.Row>
                    <Grid.Column>
                        {createPlaySoundButton()}
                        <Button onClick={goBack} className={"fullWidth marginTopSmall"}>{t("goBack")}</Button>
                    </Grid.Column>
                </Grid.Row>
            </Grid>
            <MIDISounds ref={midiSounds} appElementName="root" instruments={[3]} />
        </div>
    );
};

export default AskChord;