
 export const dictations = [
 
// simple ---------------------------------------------
		{category: "degrees_level1", title: "1",
            degrees: "1 2 3 2 1 -7 1 ",
            tonicVtNote: "C/5", // kas vaja
            scale: "major",
        },
        {category: "degrees_level1", title: "2",
            tonicVtNote: "C/5",
            degrees: "1 2 1 -7   -6 -5 1 ",
            scale: "major",
        },
        {category: "degrees_level1", title: "3",
            tonicVtNote: "C/4",
            degrees: "1 2 3 4 5 6 5 ",
            scale: "major",
        },
        {category: "degrees_level1", title: "4",
            tonicVtNote: "C/5",
            degrees: "1 2 3 4 3 2 3 ",
            scale: "major",
        },
        {category: "degrees_level1", title: "5",
            tonicVtNote: "G/4",
            degrees: "1 -7   -6 -5 1 2 3 ",
            scale: "major",
        },

        {category: "degrees_level1", title: "6",
            tonicVtNote: "G/4",
            degrees: "1 -7 1 2  3 4 3 ",
            scale: "major",
        },
        {category: "degrees_level1", title: "7",
            tonicVtNote: "G/4",
            degrees: "1 2 3 4 5 1 -7 ",
            scale: "major",
        },
        {category: "degrees_level1", title: "8",
            tonicVtNote: "G/4",
            degrees: "1 2 3 1 3 4 5 ",
            scale: "major",
        },
        {category: "degrees_level1", title: "9",
            tonicVtNote: "F/4",
            degrees: "1 2 3 5 4 2 3  ",
            scale: "major",
        },
        {category: "degrees_level1", title: "10",
            tonicVtNote: "/4",
            degrees: "1 3 5 4 3 5 1 ",
            scale: "major",
        },
 
];
